//! The eleven starting characters, and the equipment they wear.
//!
//! Generated from `runtime-pack/battle/{characters,equipment}.json` — the pack
//! the extractor proves against the retail image — so nothing here is
//! transcribed by hand. Each record is paired with the pack's own
//! `initialized` vector: what the cartridge's `InitializeCharStats`
//! (`$0044652`) leaves in RAM after it runs `UpdateCharModStats` and
//! `UpdateCharElems`. Seating a record and comparing against that vector is the
//! conformance test for both derivation passes.
//!
//! `psiv-core` cannot read the pack, so the numbers live here; the matching
//! `psiv-data` integration test pins the same vectors against the live file, so
//! a drift on either side fails loudly rather than silently agreeing.

use super::records::{Bonuses, CharacterRecord, ItemKind, ItemRecord};

/// What a seated character's stats must come out as.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Initialized {
    /// `Character_Stats` index.
    pub character: u8,
    /// Base and equipment-modified strength, mental, agility, dexterity.
    pub base: [u8; 4],
    /// The same four after `UpdateCharModStats`.
    pub modified: [u8; 4],
    /// `atk_pow`, `dfs_pow`, `magic_dfs`.
    pub derived: [u16; 3],
    /// The fourteen finished element properties, in record order.
    pub element_props: [u8; 14],
    /// `$50` and `$51`.
    pub weapon_elements: [u8; 2],
}

/// Every item the eleven starting loadouts name.
#[must_use]
pub fn equipment() -> Vec<ItemRecord> {
    vec![
        ItemRecord {
            id: 1,
            name: "DAGGER".into(),
            kind: ItemKind::OneHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 2,
                defence: 0,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 2,
            name: "HUNT-KNIFE".into(),
            kind: ItemKind::OneHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 5,
                defence: 0,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 3,
            name: "BOOMERANG".into(),
            kind: ItemKind::OneHandedMultiTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 1,
                defence: 0,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 4,
            name: "LTHR-CLOTH".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 2,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 5,
            name: "LTHR-HELM".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 1,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 6,
            name: "LTHR-CROWN".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 1,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 7,
            name: "LTHR-BAND".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 1,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 10,
            name: "LTHRSHIELD".into(),
            kind: ItemKind::Shield,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 2,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 15,
            name: "CIRCLET".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 2,
                mental_defence: 1,
            },
            element: 0,
        },
        ItemRecord {
            id: 16,
            name: "WOOD-CANE".into(),
            kind: ItemKind::TwoHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 1,
                agility: 0,
                dexterity: 0,
                attack: 4,
                defence: 0,
                mental_defence: 1,
            },
            element: 1,
        },
        ItemRecord {
            id: 17,
            name: "WHITEMANTL".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 1,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 10,
                mental_defence: 1,
            },
            element: 0,
        },
        ItemRecord {
            id: 21,
            name: "TITN-AXE".into(),
            kind: ItemKind::TwoHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 26,
                defence: 8,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 23,
            name: "TITN-MAIL".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 15,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 25,
            name: "TITN-HELM".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 7,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 28,
            name: "GRPT-SUIT".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 16,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 31,
            name: "GRPT-CROWN".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 11,
                mental_defence: 0,
            },
            element: 0,
        },
        ItemRecord {
            id: 32,
            name: "CLAW".into(),
            kind: ItemKind::OneHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 12,
                defence: 0,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 43,
            name: "IMPACTER".into(),
            kind: ItemKind::TwoHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 31,
                defence: 0,
                mental_defence: 0,
            },
            element: 1,
        },
        ItemRecord {
            id: 44,
            name: "TITN-ARMOR".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 36,
                mental_defence: 4,
            },
            element: 0,
        },
        ItemRecord {
            id: 45,
            name: "HEAD-GEAR".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 7,
                mental_defence: 1,
            },
            element: 0,
        },
        ItemRecord {
            id: 60,
            name: "SPACEDARMR".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 53,
                mental_defence: 12,
            },
            element: 0,
        },
        ItemRecord {
            id: 61,
            name: "CRMC-GEAR".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 13,
                mental_defence: 3,
            },
            element: 3,
        },
        ItemRecord {
            id: 62,
            name: "PLSM-RIFLE".into(),
            kind: ItemKind::TwoHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 73,
                defence: 0,
                mental_defence: 0,
            },
            element: 2,
        },
        ItemRecord {
            id: 68,
            name: "SILV-ROD".into(),
            kind: ItemKind::TwoHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 2,
                agility: 0,
                dexterity: 0,
                attack: 18,
                defence: 0,
                mental_defence: 5,
            },
            element: 1,
        },
        ItemRecord {
            id: 69,
            name: "SILV-MANTL".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 3,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 49,
                mental_defence: 8,
            },
            element: 0,
        },
        ItemRecord {
            id: 70,
            name: "SILVCIRCLT".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 3,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 10,
                mental_defence: 2,
            },
            element: 0,
        },
        ItemRecord {
            id: 74,
            name: "SILV-CROWN".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 16,
                mental_defence: 4,
            },
            element: 0,
        },
        ItemRecord {
            id: 88,
            name: "RFLCSHIELD".into(),
            kind: ItemKind::Shield,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 23,
                mental_defence: 16,
            },
            element: 0,
        },
        ItemRecord {
            id: 89,
            name: "RFLC-ROBE".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 58,
                mental_defence: 20,
            },
            element: 0,
        },
        ItemRecord {
            id: 91,
            name: "LACODAGGER".into(),
            kind: ItemKind::OneHandedSingleTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 39,
                defence: 0,
                mental_defence: 0,
            },
            element: 2,
        },
        ItemRecord {
            id: 93,
            name: "LACOSLASHR".into(),
            kind: ItemKind::OneHandedMultiTarget,
            bonuses: Bonuses {
                strength: 0,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 30,
                defence: 0,
                mental_defence: 0,
            },
            element: 2,
        },
        ItemRecord {
            id: 106,
            name: "LACOCIRCLT".into(),
            kind: ItemKind::Headwear,
            bonuses: Bonuses {
                strength: 0,
                mental: 4,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 12,
                mental_defence: 4,
            },
            element: 0,
        },
        ItemRecord {
            id: 108,
            name: "CYBER-SUIT".into(),
            kind: ItemKind::Body,
            bonuses: Bonuses {
                strength: 5,
                mental: 0,
                agility: 0,
                dexterity: 0,
                attack: 0,
                defence: 50,
                mental_defence: 0,
            },
            element: 0,
        },
    ]
}

/// The eleven `InitialCharStats` records.
#[must_use]
pub fn records() -> Vec<CharacterRecord> {
    vec![
        CharacterRecord {
            id: 0,
            name: "Chaz".into(),
            profession: 0,
            level: 1,
            experience: 0,
            hp: 25,
            max_hp: 25,
            tp: 10,
            max_tp: 10,
            strength: 8,
            mental: 6,
            agility: 7,
            dexterity: 5,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [2, 2, 5, 4],
        },
        CharacterRecord {
            id: 1,
            name: "Alys".into(),
            profession: 0,
            level: 7,
            experience: 2457,
            hp: 53,
            max_hp: 53,
            tp: 40,
            max_tp: 40,
            strength: 12,
            mental: 12,
            agility: 15,
            dexterity: 13,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [3, 0, 6, 4],
        },
        CharacterRecord {
            id: 2,
            name: "Hahn".into(),
            profession: 1,
            level: 1,
            experience: 0,
            hp: 21,
            max_hp: 21,
            tp: 25,
            max_tp: 25,
            strength: 6,
            mental: 8,
            agility: 4,
            dexterity: 5,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [1, 10, 7, 4],
        },
        CharacterRecord {
            id: 3,
            name: "Rune".into(),
            profession: 2,
            level: 17,
            experience: 43379,
            hp: 93,
            max_hp: 93,
            tp: 136,
            max_tp: 136,
            strength: 15,
            mental: 38,
            agility: 22,
            dexterity: 21,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [16, 0, 15, 17],
        },
        CharacterRecord {
            id: 4,
            name: "Gryz".into(),
            profession: 3,
            level: 6,
            experience: 1046,
            hp: 66,
            max_hp: 66,
            tp: 20,
            max_tp: 20,
            strength: 18,
            mental: 8,
            agility: 6,
            dexterity: 11,
            properties: [2, 2, 1, 2, 3, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [21, 0, 25, 23],
        },
        CharacterRecord {
            id: 5,
            name: "Rika".into(),
            profession: 4,
            level: 1,
            experience: 0,
            hp: 39,
            max_hp: 39,
            tp: 25,
            max_tp: 25,
            strength: 13,
            mental: 11,
            agility: 13,
            dexterity: 11,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [32, 32, 31, 28],
        },
        CharacterRecord {
            id: 6,
            name: "Demi".into(),
            profession: 5,
            level: 12,
            experience: 12137,
            hp: 96,
            max_hp: 96,
            tp: 0,
            max_tp: 0,
            strength: 28,
            mental: 0,
            agility: 26,
            dexterity: 25,
            properties: [2, 2, 1, 2, 1, 2, 3, 0, 2, 0, 0, 2, 0, 2],
            equipment: [43, 0, 45, 44],
        },
        CharacterRecord {
            id: 7,
            name: "Wren".into(),
            profession: 5,
            level: 20,
            experience: 64207,
            hp: 210,
            max_hp: 210,
            tp: 0,
            max_tp: 0,
            strength: 51,
            mental: 0,
            agility: 38,
            dexterity: 39,
            properties: [2, 2, 1, 2, 1, 2, 3, 0, 2, 0, 0, 2, 0, 2],
            equipment: [62, 0, 61, 60],
        },
        CharacterRecord {
            id: 8,
            name: "Raja".into(),
            profession: 6,
            level: 25,
            experience: 137194,
            hp: 108,
            max_hp: 108,
            tp: 170,
            max_tp: 170,
            strength: 31,
            mental: 51,
            agility: 24,
            dexterity: 30,
            properties: [2, 2, 3, 2, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [68, 0, 70, 69],
        },
        CharacterRecord {
            id: 9,
            name: "Kyra".into(),
            profession: 7,
            level: 27,
            experience: 155036,
            hp: 159,
            max_hp: 159,
            tp: 122,
            max_tp: 122,
            strength: 37,
            mental: 43,
            agility: 35,
            dexterity: 40,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            equipment: [93, 88, 74, 89],
        },
        CharacterRecord {
            id: 10,
            name: "Seth".into(),
            profession: 1,
            level: 35,
            experience: 424173,
            hp: 233,
            max_hp: 233,
            tp: 0,
            max_tp: 0,
            strength: 50,
            mental: 63,
            agility: 50,
            dexterity: 50,
            properties: [2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 0, 0, 2],
            equipment: [91, 88, 106, 108],
        },
    ]
}

/// The pack's `initialized` conformance vectors, in the same order.
#[must_use]
pub fn expected() -> Vec<Initialized> {
    vec![
        Initialized {
            character: 0,
            base: [8, 6, 7, 5],
            modified: [8, 6, 7, 5],
            derived: [18, 10, 6],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 1],
        },
        Initialized {
            character: 1,
            base: [12, 12, 15, 13],
            modified: [12, 12, 15, 13],
            derived: [13, 18, 12],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 2,
            base: [6, 8, 4, 5],
            modified: [6, 8, 4, 5],
            derived: [8, 9, 8],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 3,
            base: [15, 38, 22, 21],
            modified: [15, 40, 22, 21],
            derived: [19, 34, 43],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 4,
            base: [18, 8, 6, 11],
            modified: [18, 8, 6, 11],
            derived: [44, 36, 8],
            element_props: [2, 2, 1, 2, 3, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 5,
            base: [13, 11, 13, 11],
            modified: [13, 11, 13, 11],
            derived: [37, 40, 11],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 1],
        },
        Initialized {
            character: 6,
            base: [28, 0, 26, 25],
            modified: [28, 0, 26, 25],
            derived: [59, 69, 5],
            element_props: [2, 2, 1, 2, 1, 2, 3, 0, 2, 0, 0, 2, 0, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 7,
            base: [51, 0, 38, 39],
            modified: [51, 0, 38, 39],
            derived: [124, 104, 15],
            element_props: [2, 2, 1, 2, 1, 2, 3, 0, 2, 0, 0, 2, 0, 2],
            weapon_elements: [2, 0],
        },
        Initialized {
            character: 8,
            base: [31, 51, 24, 30],
            modified: [31, 59, 24, 30],
            derived: [49, 83, 74],
            element_props: [2, 2, 3, 2, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [1, 0],
        },
        Initialized {
            character: 9,
            base: [37, 43, 35, 40],
            modified: [37, 43, 35, 40],
            derived: [67, 132, 83],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2],
            weapon_elements: [2, 0],
        },
        Initialized {
            character: 10,
            base: [50, 63, 50, 50],
            modified: [55, 67, 50, 50],
            derived: [94, 135, 87],
            element_props: [2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 0, 0, 2],
            weapon_elements: [2, 0],
        },
    ]
}
