#!/usr/bin/env python3
"""Characterise what an accept press does inside the dialogue open animation.

Tape 03 pins the timing: Speak at f7185, Window_Render_Mode goes $0600 at
f7187, and Windows_Opened_Num reaches 1 at f7196. A press inside that window is
known to be consumed rather than dropped, but "consumed" was measured from a
single offset. This sweeps the offset across the animation and past it, and
reports the text-draw frames each one produces, so the renderer fix can
implement the measured behaviour instead of a guess.

The measurement is Text_Buffer ($FFFF7000) writes, not the window flag: the
flag cannot distinguish a consumed press from a dropped one, and both a real
talk and the "nothing here" whiff open a window.
"""
import csv
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
O = ROOT / "oracle"
BIN = O / "bin" / "psiv_oracle"
CORE = O / "core" / "genesis_plus_gx_libretro.so"
ROM = ROOT / "Phantasy Star IV (USA).md"

# Everything in tape 03 up to and including its Speak press.
HEAD = (O / "tapes" / "03_npc_talk.tape").read_text().split("4 C speak")[0] \
    + "4 C speak\n"

PROBE_MAP = O / "tmp_anim_map.tsv"
NCOLS = 24


def write_probe_map():
    lines = ["# GENERATED by oracle/scripts/anim_sweep.py",
             "# name\taddr\tsize\tgroup\tflags",
             "win_open\tFFFFEC9A\t1\tw\t-",
             "render_mode\tFFFFEC9C\t2\tw\thex"]
    for i in range(NCOLS):
        lines.append(f"tb{i:02d}\t{0xFFFF7000 + i * 4:08X}\t4\tw\thex")
    PROBE_MAP.write_text("\n".join(lines) + "\n")


def run(gap):
    """gap = frames of nothing between the Speak step and the probe press.

    None means no press at all: the control.
    """
    if gap is None:
        body = "700 . watch\n"
    else:
        body = (f"{gap} . gap\n" if gap else "") + "4 C press\n700 . watch\n"
    tape = O / "tmp_anim.tape"
    tape.write_text(HEAD + body)
    out = O / "logs" / "anim_sweep.csv"
    subprocess.run([str(BIN), "--core", str(CORE), "--rom", str(ROM),
                    "--map", str(PROBE_MAP), "--tape", str(tape),
                    "--out", str(out)], check=True, capture_output=True)
    rows = list(csv.DictReader([l for l in open(out) if not l.startswith('#')]))
    byf = {int(r['frame']): r for r in rows}
    speak = next(int(r['frame']) for r in rows if r['mark'] == 'speak')
    press = next((int(r['frame']) for r in rows if r['mark'] == 'press'), None)
    opened = next((int(r['frame']) for r in rows
                   if int(r['frame']) > speak and r['win_open'] != '0'), None)
    text = lambda f: tuple(byf[f][f'tb{i:02d}'] for i in range(NCOLS))
    draws = [f for f in range(speak, speak + 120)
             if f in byf and f - 1 in byf and text(f) != text(f - 1)]
    return speak, press, opened, draws


def main():
    write_probe_map()
    speak, _, opened, base = run(None)
    print(f"Speak at f{speak}; window opens at f{opened} "
          f"(animation f{speak + 2}-f{opened})")
    print(f"control draw frames: {[f - opened for f in base]} (relative to open)")
    print()
    print(f"{'press':>7} {'rel':>5} {'in anim':>8} {'draws':>6}  "
          f"draw frames relative to window open")
    for gap in range(0, 16):
        s, p, o, draws = run(gap)
        rel = p - s
        inside = s + 2 <= p <= o
        rels = [f - o for f in draws]
        extra = len(draws) - len(base)
        mark = f"{extra:+d}" if extra else " 0"
        print(f"f{p:<6} {rel:>5} {'yes' if inside else 'no':>8} "
              f"{len(draws):>3} {mark}  {rels[:14]}")


if __name__ == "__main__":
    main()
