#!/usr/bin/env python3
"""Emit the flat ram_map.tsv the C host reads from the canonical ram_map.json.

ram_map.json is the source of truth (it carries the disassembly citations and
is what Rust/Python consumers should read). The C host wants something it can
parse without a JSON dependency, so this generates it. oracle/verify.sh
regenerates and diffs, which is what stops the two from drifting apart.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def main() -> int:
    src = HERE / "ram_map.json"
    dst = HERE / "ram_map.tsv"
    doc = json.loads(src.read_text())

    seen: dict[str, str] = {}
    lines = [
        "# GENERATED by gen_ram_map.py from ram_map.json - do not edit.",
        "# name<TAB>addr<TAB>size<TAB>group<TAB>flags",
    ]
    for f in doc["fields"]:
        name = f["name"]
        if name in seen:
            print(f"duplicate field name {name!r}", file=sys.stderr)
            return 1
        seen[name] = f["addr"]

        addr = int(f["addr"], 16)
        size = int(f["size"])
        if size not in (1, 2, 4):
            print(f"{name}: bad size {size}", file=sys.stderr)
            return 1
        if addr < 0xFFFF0000 or addr > 0xFFFFFFFF:
            print(f"{name}: {f['addr']} is outside 68000 work RAM",
                  file=sys.stderr)
            return 1
        if size in (2, 4) and addr % 2:
            print(f"{name}: {f['addr']} is an odd address for a "
                  f"{size}-byte read", file=sys.stderr)
            return 1

        flags = []
        if f.get("hex"):
            flags.append("hex")
        if f.get("signed"):
            flags.append("signed")
        lines.append("\t".join([
            name, f["addr"], str(size), f.get("group", "misc"),
            ",".join(flags) if flags else "-",
        ]))

    dst.write_text("\n".join(lines) + "\n")
    print(f"wrote {dst} ({len(doc['fields'])} fields)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
