#!/usr/bin/env python3
"""Author a walking tape by closed-loop planning against the emulator.

route.py plans over the extracted collision grid alone, which is enough for
terrain but not for NPCs: field objects also block, they block a taller
footprint than the terrain grid models, and they wander, so a route planned
once can be blocked by an NPC that was somewhere else when it was planned.

This drives the loop instead. It plans a leg, runs the tape, reads where the
character actually ended up out of the log, and re-plans from there with the
observed object footprints marked blocked. Cells that repeatedly refuse to
admit the character get blacklisted so the planner goes around.

The feedback happens at *authoring* time. What comes out the other end is an
ordinary static tape with no runtime feedback in it at all, so it still
replays byte-identically like every other tape in oracle/tapes/.
"""
import argparse
import csv
import pathlib
import subprocess

import route as R

ROOT = pathlib.Path(__file__).resolve().parent.parent
ORACLE = ROOT / "oracle"
BIN = ORACLE / "bin" / "psiv_oracle"
CORE = ORACLE / "core" / "genesis_plus_gx_libretro.so"
ROM = ROOT / "Phantasy Star IV (USA).md"
MAP = ORACLE / "ram_map.tsv"

# Objects occupy more than the single cell their position reports: an NPC
# whose curr_y_pos is on pixel row R was observed blocking a character trying
# to enter pixel row R+1, so both rows are treated as occupied.
OBJ_FOOTPRINT = [(0, 0), (0, 1)]

OBJ_BASE, OBJ_STRIDE, OBJ_COUNT = 0xFFFFC300, 0x40, 12


def write_probe_map(path):
    """A RAM map with the character plus every secondary field object."""
    lines = ["# GENERATED by navigate.py", "# name\taddr\tsize\tgroup\tflags",
             "map_index\tFFFFEC28\t2\tcore\thex",
             "game_mode\tFFFFEF00\t2\tcore\thex",
             "game_mode_routine\tFFFFEC20\t2\tcore\thex",
             "c1_x_px\tFFFFC030\t2\tcore\t-",
             "c1_y_px\tFFFFC034\t2\tcore\t-"]
    for i in range(OBJ_COUNT):
        b = OBJ_BASE + i * OBJ_STRIDE
        lines.append(f"o{i}_x\t{b + 0x30:08X}\t2\tnpc\t-")
        lines.append(f"o{i}_y\t{b + 0x34:08X}\t2\tnpc\t-")
    path.write_text("\n".join(lines) + "\n")


def run(tape, out, probe_map):
    subprocess.run([str(BIN), "--core", str(CORE), "--rom", str(ROM),
                    "--map", str(probe_map), "--tape", str(tape),
                    "--out", str(out)], check=True, capture_output=True)
    rows = list(csv.DictReader(
        [l for l in open(out) if not l.startswith("#")]))
    last = rows[-1]
    occupied = set()
    for i in range(OBJ_COUNT):
        x, y = int(last[f"o{i}_x"]), int(last[f"o{i}_y"])
        if x or y:
            for dx, dy in OBJ_FOOTPRINT:
                occupied.add((x // 16 + dx, y // 16 + dy))
    return (int(last["map_index"], 16),
            int(last["c1_x_px"]) // 16, int(last["c1_y_px"]) // 16,
            occupied)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prelude", required=True,
                    help="tape whose end state the walk starts from")
    ap.add_argument("--to-map", type=lambda s: int(s, 0), required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--pack", default=str(ROOT / "runtime-pack"))
    ap.add_argument("--max-iters", type=int, default=40)
    a = ap.parse_args()

    maps = R.load_pack(a.pack)
    probe_map = ORACLE / "tmp_nav_map.tsv"
    write_probe_map(probe_map)

    body = "\n120 . nav_settle\n"
    tape = ORACLE / "tmp_nav.tape"
    log = ORACLE / "logs" / "nav_probe.csv"
    prelude = pathlib.Path(a.prelude).read_text().rstrip() + "\n"

    blacklist = set()
    tape.write_text(prelude + body)
    mid, x, y, occ = run(tape, log, probe_map)
    print(f"start: map ${mid:02X} cell ({x},{y})")

    MAX_LEG = 12   # short legs so a blockage is localised to a few cells
    stalls = 0

    for it in range(a.max_iters):
        if mid == a.to_map:
            print(f"reached map ${mid:02X} after {it} legs")
            break

        blocked = {(mid, cx, cy) for (cx, cy) in occ} | blacklist
        path = R.plan(maps, (mid, x, y), a.to_map, blocked=blocked)
        if path is None:
            print(f"no route from ${mid:02X} ({x},{y}); giving up")
            return 1

        # A leg is a short prefix, ending at a map change if one comes first.
        leg, crossed = [], False
        for step in path:
            leg.append(step)
            if step[1] == '*':
                crossed = True
                break
            if len(leg) >= MAX_LEG:
                break

        # Where the leg is supposed to end: the cell the last step moves into,
        # or the warp destination when the leg crosses a map.
        if crossed:
            want = None            # destination known only to the pack; just
        else:                      # accept any map change as success
            (m0, cx, cy), letter = leg[-1]
            ddx, ddy = {'U': (0, -1), 'D': (0, 1), 'L': (-1, 0), 'R': (1, 0)}[letter]
            want = (m0, cx + ddx, cy + ddy)

        lines = R.to_tape(leg)
        if not lines:
            print("planner produced an empty leg; giving up")
            return 1
        # A map change costs a fade plus a load; 120 frames was not always
        # enough for the character to be movable again on the far side, which
        # showed up as a leg that appeared to make no progress at all.
        chunk = "\n".join(lines) + "\n" + ("300 . cross\n" if crossed
                                            else "30 . rest\n")
        tape.write_text(prelude + body + chunk)
        nmid, nx, ny, occ = run(tape, log, probe_map)

        arrived = (nmid != mid) if crossed else ((nmid, nx, ny) == want)
        if arrived:
            body += chunk
            stalls = 0
            print(f"  leg {it}: ${mid:02X} ({x},{y}) -> ${nmid:02X} ({nx},{ny})")
            mid, x, y = nmid, nx, ny
            continue

        # The leg did not land where the grid said it would. Blacklist the cell
        # the character failed to enter - the next one along the planned path
        # from wherever it actually stopped - and re-plan around it.
        print(f"  leg {it}: ${mid:02X} ({x},{y}) -> ${nmid:02X} ({nx},{ny}) "
              f"[wanted {want}]")
        cells = [(m0, cx, cy) for (m0, cx, cy), _ in leg]
        stop_at = None
        if (nmid, nx, ny) in cells:
            i = cells.index((nmid, nx, ny))
            if i + 1 < len(leg):
                (m0, cx, cy), letter = leg[i + 1 if i + 1 < len(leg) else i]
                stop_at = (m0, cx, cy)
            else:
                (m0, cx, cy), letter = leg[-1]
                ddx, ddy = {'U': (0, -1), 'D': (0, 1),
                            'L': (-1, 0), 'R': (1, 0)}[letter]
                stop_at = (m0, cx + ddx, cy + ddy)
        if stop_at is None or stop_at in blacklist:
            stop_at = want
        if stop_at is None or stop_at in blacklist:
            stalls += 1
            if stalls > 3:
                print("  stalled with nothing new to blacklist; giving up")
                return 1
        else:
            blacklist.add(stop_at)
            print(f"    blacklisted {stop_at}")
        # Keep whatever ground the character did gain.
        if (nmid, nx, ny) != (mid, x, y):
            body += chunk
            mid, x, y = nmid, nx, ny
    else:
        print("hit the iteration limit without arriving")
        return 1

    pathlib.Path(a.out).write_text(prelude + body)
    frames = sum(int(l.split()[0]) for l in (prelude + body).splitlines()
                 if l.strip() and not l.startswith(("#", "repeat", "end")))
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
