//! The core's central promise: the same state, map and input sequence produce
//! the same state and the same effect log, every run, forever.
//!
//! The scripts below are generated by a tiny in-test LCG rather than a random
//! crate, so the "arbitrary" input is itself reproducible and the test has no
//! dependencies.

mod common;

use common::{map_with, npc, party};
use psiv_core::{Cell, Direction, Effect, FieldMap, FieldState, Input, MapId, Warp};

/// A deterministic input script: a 32-bit LCG mapped onto the five inputs.
fn input_script(seed: u32, length: usize) -> Vec<Input> {
    let mut state = seed;
    let mut script = Vec::with_capacity(length);
    for _ in 0..length {
        state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        script.push(match (state >> 16) % 5 {
            0 => Input::Neutral,
            1 => Input::Direction(Direction::Up),
            2 => Input::Direction(Direction::Down),
            3 => Input::Direction(Direction::Left),
            _ => Input::Direction(Direction::Right),
        });
    }
    script
}

/// A cluttered map with walls of every blocking type, two doorways (one of them
/// deliberately unmapped) and NPCs, so a long script hits every branch.
fn cluttered_map() -> FieldMap {
    // Kept one row per line: the map is a picture, and reading it as one is the
    // whole point of the ASCII fixtures.
    #[rustfmt::skip]
    let rows = [
        "..D..#..",
        ".##.~..$",
        "....s...",
        ".i..#...",
        "...##...",
        "D..D....",
        "..#.~~..",
        "........",
    ];
    // Only the doorway at (3, 5) is mapped. The ones at (0, 5) and (2, 0) are
    // type-1 cells no transition covers, so the script surfaces them as
    // WarpUnmapped rather than tripping over them.
    let warps = vec![Warp::door(
        Cell::new(3, 5),
        MapId(0x13),
        Cell::new(1, 1),
        Direction::Down,
    )];
    map_with(&rows, warps, vec![npc(1, 3, 2), npc(2, 5, 5), npc(3, 0, 7)])
}

/// Replays a script and returns the resulting state plus the full effect log,
/// each effect tagged with the tick it came from.
fn replay(script: &[Input]) -> (FieldState, Vec<(usize, Effect)>) {
    let map = cluttered_map();
    let mut state = party(&map, 1, 5);
    let mut log = Vec::new();
    for (tick, &input) in script.iter().enumerate() {
        for effect in state.tick(&map, input) {
            log.push((tick, effect));
        }
    }
    (state, log)
}

#[test]
fn replaying_a_two_hundred_tick_script_is_bit_identical() {
    let script = input_script(0xC0FFEE, 200);

    let (first_state, first_log) = replay(&script);
    let (second_state, second_log) = replay(&script);

    assert_eq!(first_state, second_state);
    assert_eq!(first_log, second_log);
    assert!(
        !first_log.is_empty(),
        "the script should actually make the party move"
    );
}

#[test]
fn many_seeds_replay_identically_and_exercise_every_effect() {
    let mut saw_step = false;
    let mut saw_warp = false;
    let mut saw_unmapped = false;

    for seed in 0..64_u32 {
        let script = input_script(seed.wrapping_mul(2_654_435_761), 200);
        let (a_state, a_log) = replay(&script);
        let (b_state, b_log) = replay(&script);
        assert_eq!(a_state, b_state, "seed {seed}");
        assert_eq!(a_log, b_log, "seed {seed}");

        for (_, effect) in &a_log {
            match effect {
                Effect::StepCompleted { .. } => saw_step = true,
                Effect::Warp { .. } => saw_warp = true,
                Effect::WarpUnmapped { .. } => saw_unmapped = true,
            }
        }
    }

    assert!(saw_step, "no steps completed across 64 scripts");
    assert!(saw_warp, "no warp fired across 64 scripts");
    assert!(saw_unmapped, "no unmapped doorway hit across 64 scripts");
}

#[test]
fn a_long_script_never_leaves_a_legal_cell() {
    let map = cluttered_map();
    let script = input_script(0x5EED, 2_000);
    let mut state = party(&map, 1, 5);

    for (tick, &input) in script.iter().enumerate() {
        state.tick(&map, input);
        let cell = state.cell();
        assert!(
            map.grid().contains(cell),
            "tick {tick}: walked out of bounds to ({}, {})",
            cell.x,
            cell.y
        );
        assert!(
            map.is_walkable(cell),
            "tick {tick}: stood on a blocked cell ({}, {})",
            cell.x,
            cell.y
        );
        let (dx, dy) = state.render_offset_16ths();
        assert!(
            dx.abs() < 16 && dy.abs() < 16,
            "tick {tick}: render offset ({dx}, {dy}) left the cell"
        );
        assert!(
            dx == 0 || dy == 0,
            "tick {tick}: render offset ({dx}, {dy}) is diagonal"
        );
    }
}

#[test]
fn state_carries_no_hidden_history() {
    // Two parties that arrive at the same cell by different routes, with no
    // step in flight, must be indistinguishable.
    let map = cluttered_map();

    let mut walked = party(&map, 1, 5);
    for _ in 0..8 {
        walked.tick(&map, Input::Direction(Direction::Right));
    }
    for _ in 0..8 {
        walked.tick(&map, Input::Direction(Direction::Left));
    }

    let placed = party(&map, 1, 5);
    let mut placed = placed;
    placed
        .enter_map(&map, Cell::new(1, 5), Direction::Left)
        .expect("valid placement");

    assert_eq!(walked, placed);
}
