[package]
name = "psiv-campaign"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
name = "psiv_campaign"
path = "src/lib.rs"

[[bin]]
name = "psiv-campaign"
path = "src/main.rs"

[dependencies]
psiv-core = { path = "../psiv-core" }
psiv-data = { path = "../psiv-data" }
psiv-runtime = { path = "../psiv-runtime" }
serde.workspace = true
serde_json.workspace = true
